title:              Pirates Treasure
email:              farhan.shakeel78600@gmail.com
description:        Anything you want from studies,drawing to code.
author:             Farhan Shakeel
baseurl:            "/pirates-treasure"
url:                "https://farhan786555.github.io/pirates-treasure"

# Social Profiles
twitter_username:   
github_username: Farhan786555   
facebook_username: Farhan Shakeel 
linkedin_username:
instagram_username: ultimate_pirate786

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-157383541-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
